round_usdt = {'ETH': 5, 'LTC': 5, 'BNB': 4, 'NEO': 3, 'QTUM': 3, 'EOS': 2, 'BNT': 2, 'BTC': 6, 'DNT': 1, 'WTC': 2,
              'LRC': 1,
              'OMG': 2, 'ZRX': 2, 'KNC': 3, 'FUN': 0, 'IOTA': 2, 'LINK': 3, 'MTL': 2, 'ETC': 3, 'ZEC': 5, 'DASH': 5,
              'BTG': 3,
              'TRX': 1, 'XRP': 2, 'ENJ': 2, 'STORJ': 2, 'KMD': 2, 'NULS': 2, 'XMR': 5, 'BAT': 2, 'GXS': 2, 'BTS': 1,
              'LSK': 2,
              'MANA': 2, 'ADA': 2, 'XLM': 1, 'WAVES': 3, 'GTO': 1, 'ICX': 2, 'AION': 2, 'RLC': 2, 'IOST': 0, 'NANO': 2,
              'BLZ': 1,
              'ZIL': 1, 'ONT': 2, 'XEM': 2, 'WAN': 2, 'REP': 3, 'TUSD': 2, 'ZEN': 4, 'CVC': 1, 'THETA': 3, 'IOTX': 0,
              'DATA': 1,
              'SC': 0, 'KEY': 0, 'MFT': 0, 'DENT': 0, 'ARDR': 1, 'HOT': 0, 'VET': 1, 'DOCK': 0, 'PAX': 2, 'RVN': 1,
              'DCR': 4,
              'USDC': 2, 'MITH': 1, 'REN': 1, 'BTT': 0, 'USDS': 2, 'ONG': 2, 'FET': 1, 'CELR': 1, 'MATIC': 1, 'ATOM': 3,
              'TFUEL': 1,
              'ONE': 1, 'FTM': 1, 'ALGO': 2, 'DOGE': 1, 'DUSK': 2, 'ANKR': 1, 'WIN': 0, 'COS': 1, 'COCOS': 2, 'TOMO': 2,
              'PERL': 1,
              'CHZ': 1, 'BAND': 3, 'BEAM': 2, 'XTZ': 2, 'HBAR': 1, 'NKN': 1, 'STX': 2, 'KAVA': 2, 'ARPA': 1, 'CTXC': 2,
              'BCH': 5,
              'TROY': 0, 'VITE': 1, 'FTT': 3, 'EUR': 2, 'OGN': 2, 'DREP': 3, 'TCT': 0, 'WRX': 2, 'LTO': 1, 'MBL': 0,
              'COTI': 1,
              'STPT': 1, 'SOL': 3, 'CTSI': 1, 'HIVE': 2, 'CHR': 1, 'MDT': 1, 'STMX': 0, 'PNT': 2, 'GBP': 2, 'DGB': 1,
              'COMP': 5,
              'BKRW': 0, 'SXP': 3, 'SNX': 3, 'IRIS': 1, 'MKR': 5, 'RUNE': 3, 'AUD': 1, 'FIO': 2, 'AVA': 2, 'BAL': 3,
              'YFI': 6,
              'JST': 1, 'SRM': 2, 'ANT': 2, 'CRV': 3, 'SAND': 1, 'OCEAN': 2, 'NMR': 3, 'DOT': 3, 'LUNA': 3, 'RSR': 1,
              'PAXG': 6,
              'WNXM': 3, 'TRB': 3, 'BZRX': 2, 'SUSHI': 3, 'YFII': 6, 'KSM': 4, 'EGLD': 4, 'DIA': 3, 'UMA': 3, 'BEL': 2,
              'WING': 3,
              'UNI': 3, 'NBS': 1, 'OXT': 2, 'SUN': 3, 'AVAX': 3, 'HNT': 3, 'BAKE': 1, 'BURGER': 1, 'FLM': 2, 'CAKE': 3,
              'ORN': 3,
              'UTK': 2, 'XVS': 3, 'ALPHA': 2, 'AAVE': 4, 'NEAR': 2, 'FIL': 4, 'INJ': 3, 'AUDIO': 2, 'CTK': 2, 'AKRO': 0,
              'AXS': 2,
              'HARD': 2, 'SLP': 0, 'STRAX': 2, 'UNFI': 3, 'ROSE': 1, 'SKL': 1, 'SUSD': 2, 'GRT': 2, 'JUV': 3, 'PSG': 3,
              '1INCH': 2,
              'REEF': 0, 'OG': 3, 'ATM': 3, 'ASR': 3, 'CELO': 2, 'RIF': 2, 'BTCST': 3, 'TRU': 2, 'CKB': 0, 'TWT': 2,
              'FIRO': 3,
              'LIT': 2, 'SFP': 2, 'DODO': 3, 'ACM': 3, 'BADGER': 3, 'FIS': 3, 'OM': 2, 'POND': 2, 'DEGO': 3, 'ALICE': 2,
              'LINA': 2,
              'PERP': 3, 'RAMP': 2, 'SUPER': 3, 'CFX': 3, 'EPS': 3, 'AUTO': 6, 'TKO': 2, 'PUNDIX': 3, 'TLM': 2,
              'MIR': 3, 'BAR': 3,
              'FORTH': 3, 'SHIB': 0}
